In [7]:
stonks = pd.read_csv('stocks.csv')

In [8]:
stonks.head()

,TIPREG,DATA DO PREGAO,CODBDI,CODNEG,TPMERC,NOMRES,ESPECI,PRAZOT,MODREF,PREABE,...,TOTNEG,QUATOT,VOLTOT,PREEXE,INDOPC,DATVEN,FATCOT,PTOEXE,CODISI,DISMES
0,1,2019-01-02,2,AALR3,10,ALLIAR,ON NM,NaN,R$,13.31,...,856,264200,3523962.00,0.0,0,9999-12-31,1,0.0,BRAALRACNOR6,100
1,1,2019-01-02,96,AALR3F,20,ALLIAR,ON NM,NaN,R$,13.30,...,21,500,6661.47,0.0,0,9999-12-31,1,0.0,BRAALRACNOR6,100
2,1,2019-01-02,2,AAPL34,10,APPLE,DRN,NaN,R$,60.71,...,45,16800,1015969.00,0.0,0,9999-12-31,1,0.0,BRAAPLBDR004,127
3,1,2019-01-02,96,AAPL34F,20,APPLE,DRN,NaN,R$,61.00,...,11,282,17046.51,0.0,0,9999-12-31,1,0.0,BRAAPLBDR004,127
4,1,2019-01-02,2,ABBV34,10,ABBVIE,DRN,NaN,R$,342.84,...,1,300,102852.00,0.0,0,9999-12-31,1,0.0,BRABBVBDR001,111

In [14]:
bb_bbm

NameError: name 'bb_bbm' is not defined